### ISSUE TITLE
Quick concerns

### ISSUE THREAD

**Issue by RohanAlexander** [xgao28/election_forecast#1]
- The README overview needs to be more extensive. Think similar to an abstract.
- README needs to be updated e.g. "obtained from X."
- Fix numbering of scripts: https://github.com/xgao28/election_forecast/tree/main/scripts
- No simulation script.
- Parquet not used.
- There are far too many pointless words. Be concise. Basically the entire first sentence of the abstract could be removed. Or at least shortened. Don't say "leveraged".
- Check list of banned words and remove the ones that you've used.
- Measurement is not detailed enough.
- Data not graphed.
- Don't include raw R output - results need to be in a modelsummary table.
- Appendices need citations to be credible. Where did you get this information from?
- No citations?

**Comment by xgao28** [comment]
Thank you! We added citations, scripts, plots and the use of parquet as suggested.
