### ISSUE TITLE
Peer Review by Xuanle Zhou

### ISSUE THREAD

**Issue by Isazhou13** [xgao28/election_forecast#4]
**Summary** 
This manuscript presents a model to predict voter support for the 2024 U.S. Presidential Election, focusing on Kamala Harris and Donald Trump. It improves polling accuracy using factors like poll quality and transparency.

**Strong positive points:**

- Clear Methodology: The methodology is comprehensive and well thought out, effectively detailing the model used for analysis. 
- Strong Introduction: The introduction provides clear context and motivation for the study, making the relevance of the topic evident.
- Dealing with multicollinearity 

**Critical improvements needed:**

- Adding sketches, simulation, test simulation files. 
- Update the README file
- Delete unnecessary files
- Mention the key findings in the title, abstract and introduction

**Suggestions for improvement:**

- The files that are not useful could be delete from the folder. For example, datasheet and literature folder, which are under the Other folder. 
- Incorporate relevant academic literature to support discussions, especially in the context of the significance of the findings and the methodologies used.
- Include performance metrics for the model, such as: Root Mean Squared Error (RMSE), R-squared values
- Adding the visuals for the model such as graphs or charts, that could help illustrate findings more clearly. 
- Ensure all graphs and tables are accompanied by appropriate captions

**Evaluation:**

- Estimated overall mark:  
- [1/1] R is appropriately cited: Yes
- [1/1] Data are appropriately cited: Yes
- [1/1] Class paper: Yes 
- [1/1] LLM usage is documented: Yes
- [1/2] Title: The title is clear and effectively conveys the topic and approach used in the paper. However, it does not mention the key findings and significant outcomes of the investigation. Additionally, the subtitle has not been reviewed or addressed.
- [0/2] Author, date, and repo: In some file, the author, data and repo is not update. For example, the 04-test_analysis_data.R file 
- [2/4] Abstract: what was done, and why this matter is mentioned in the abstract. However, wat was found is not presented in the abstract. 
- [2/4] Introduction:  The introduction is strong, with clear context, motivation, and structure. It would be further improved with more specific findings and a deeper emphasis on the importance of those findings.
- [1/1] Estimand: clearly stated
- [8/10] Data: Variables is detailed discussed. Maybe more graphs can be added to provide a clearer view of what dataset looks like. Lack of summary statistics.
- [2 /4] Measurement: it needs more depth, particularly regarding how real-world polling phenomena are transformed into usable dataset entries
- [6 /10] Model: Overall good, but. the section could improve by providing details of model assumptions and limitations more comprehensively.  Also, it lack overall assessment of model performance and alternative models to consider. 
- [6 /10] Result : Lack of visual aids. The regression table should not contains stars.
- [ 8 /10] Discussion: The discussion section successfully covers the key findings, acknowledges the limitations of the analysis, and proposes thoughtful future research directions. However, it is a little bit short, more depth discussion could be better.
- [6/6] Prose: good
- [1/1] Cross-reference: Yes
- [1/2] Captions: Lack of captions for graph in section 2.4.6
- [2/4] Graphs/tables/etc: Lack of appropriate use of caption for graph in 2.4.6. Also, the model output result table is not in the Kable format. 
- [ 8 /10] Idealized methodology: This methodology is comprehensive, well thought out, and likely to achieve its goals
- [4/4] Idealized survey:  Covered every requirement 
- [8/10] Pollster methodology overview and evaluation: 
- [0/4] Reference: It is in the default folder, some libraries being used is not included into the reference yet. 
- [2/2] Commits: informative commits
-  [0/2] Sketches: Not provided
- [0/4] Simulation: Not provided
- [0/4] Tests-simulation: Not provided
- [0/1] Parquet: Not provided
- [ 1 / 4] Reproducible workflow: The README is not completely updated. The 'Some checks' section in the README file is not being deleted. The code is not in the good and most efficient style. Unnecessary files still in the repo.  
- [1 /3] Miscellaneous

**Estimated overall mark:**
70/126

**Any other comments:**
None. I am confident that with thorough refinement, this paper has the potential to be outstanding.

**Comment by xgao28** [comment]
Thank you! We fixed the improvements you addressed in some of our latest commits.
