### ISSUE TITLE
Peer review from Lorina Yang

### ISSUE THREAD

**Issue by Lorina-Y** [xgao28/election_forecast#6]
I am Lorina Yang, and I’m peer-reviewing the paper on “Forecasting the 2024 US Presidential Election: A Poll-Based Approach"
The feedback below conducted at 11:50 on Oct 23, 2024
**Opening Statement Summary:**
This paper presents a forecasting model for the 2024 U.S. Presidential Election, predicting voter support for Kamala Harris and Donald Trump using polling data. Through multiple linear regression, it incorporates factors like poll quality, sample size, geographic variation, and trends over time to estimate each candidate's share of support.

**Strong Positive Points:**
1.	Clear research focus: The paper demonstrates a focused and well-structured approach to analyzing voter support in the 2024 U.S. Presidential Election. By centering on key factors such as poll quality, transparency, sample size, geographic variation, and temporal trends, the research offers a clear objective of predicting candidate support and clearly state the model use (MLR). 
2.	Use of Table of Content:  The inclusion of a well-organized table of contents at the beginning of the paper is a notable strength. It helps readers navigate the document efficiently, improving its overall readability. Additionally, the clear organization of information in the two appendix sections demonstrates a thoughtful approach to presenting the survey methods and analysis.

**Critical Improvements Needed:**
1.	README section:The README would benefit from including more detailed information about the objectives of the paper, specifically outlining the key research questions or goals, and provide a clear explanation of the models used. Additionally, the README should explain the data sources, steps involved in data cleaning, and how the code is organized for enhance reproducibility and transparency. 
2.	Model setup:The inclusion of the categorical variable "state" in your multiple linear regression model results in a large number of coefficients, one for each state. This can lead to redundancy and make the model harder to interpret. Instead of displaying every state individually, consider cleaning the data by grouping states into broader categories such as North, West, South, and East, or focus on a subset of key states that provide the most observations. This will simplify the model, improve clarity, and still capture the regional differences in voter behavior.
3.	Results Section: Give more detailed explanations related to the specific data presented in your multiple linear regression (MLR) model table. Provide a clear interpretation of the key coefficients, explaining how each predictor variable (such as poll quality, sample size, geographic variation, etc.) influences voter support for the candidates. Highlight any significant findings or trends, particularly focusing on the most impactful predictors. 
4. Expand your discussion section: Even with the inclusion of weaknesses and future directions, you can still enrich the discussion by offering more detailed interpretations of your key findings. Highlight the most significant predictors from your model and explain their broader implications for understanding voter behavior and electoral trends. Discuss any unexpected results and explore possible reasons for these outcomes. 
5.  Remove unnecessary file in Repository: It's important to removing any unnecessary files that don't contribute directly to the analysis, such as the “literature” file under “other” which not related to your paper. This will make the repository more organized and easier to navigate. Additionally, ensure that the README is updated to reflect any changes, to maintain consistency and clarity regarding their purpose and usage within the project. 

**Suggestions for Improvement:**
- Carefully proofread the document to ensure there are no grammatical errors or typos.
- Update the README with more detailed information about the project's objectives and methodology.
- Revise and complete the reference.bib section to ensure all citations are properly included.
- Add additional visualizations to help illustrate the key findings more effectively.
- Integrate relevant academic literature to strengthen the discussions and support the significance of the findings and methodologies used.
 
**Evaluation:**
R is appropriately cited | 1/1
Data are appropriately cited | 1/1
Class paper | 1/1
LLM usage is documented | 1/1
Title | 1/2
Author, date, and repo | 0/2
Abstract | 3/4
Introduction | 2/4
Estimand | 1/1
Data | 8/10
Measurement |8 /10
Model | 8/10
Results | 5/10
Discussion | 6/10
Prose | 6/6
Cross-references | 1/1
Captions | 2/2
Graphs/tables/etc | 3/4
Idealized methodology | 10/10
Idealized survey | 4/4
Pollster methodology overview and evaluation | 7/10
Referencing | 1/4
Commits | 2/2
Sketches | 0/2
Simulation | 2/4
Tests-simulation: 3/4
Tests-actual | 2/4
Parquet | 1/1
Reproducible workflow | 2/4
Miscellaneous | 2/3
Overall: 94/126 

**Reasoning:**
The project is nearly complete and well-developed, but a few adjustments are still needed. The reference section requires updating, as it currently remains in its default state. Additionally, the README file should be expanded to provide more detailed information about the project’s goals, models used, and how reproducibility and transparency are ensured. Addressing these issues will enhance the overall quality and professionalism of the project.

**Comment by xgao28** [comment]
Thank you! We addressed the concern mentioned above in a few commits.
