### ISSUE TITLE
Quick comments

### ISSUE THREAD

**Issue by RohanAlexander** [xgao28/election_forecast#8]
- R is appropriately cited (0/1)
	- No. Paper shoudl get zero.
- Data are appropriately cited (0/1)
	- No. Paper shoudl get zero.
- Class paper (-/1)
	- Yes.
- LLM usage is documented (1/1)
	- Yes
- Title (1/2)
	- "Kamala Harris Poised for Victory" - That's a subtitle that a newspaper would use. Be more specific and scientific.
- Author, date, and repo (2/2)
	- Good
- Abstract (2/4)
	- Re-write.
- Introduction (2/4)
	- This writing is unreadable. The underlying content is good, but be concise and specific.
- Estimand (0/1)
	- Move this into a paragraph in the introduction not it's own subsection.
- Data (3/10)
	- Why do you not plot all the variables you're interested in?
- Measurement (0/4)
	- The fundamental measurement problem is that you are trying to go from an opinion in someone's head about who they are going to vote for to an estimate of the number of electoral college votes they get. That does not come across here at all.
- Model (5/10)
	- It is not clear to me what you are modelling here. I'd recommend that you have someone else in the group read this and try to explain it to the person who did the modelling. If they can't then this isn't appropriately explained.
- Results (5/10)
	- Use modelsummary tables.
	- Do not have silly amounts of decimal places. Two or three maximum
- Discussion (5/10)
	- More. 
- Prose (0/6)
	- Don't use words/phrases that I asked you not to use. e.g. offering insights.
- Cross-references (0/1)
	- Tables 1 and 2 are not referred to in the text.
- Captions (0/2)
	- More detail please.
- Graphs/tables/etc (3/4)
	- Good.
- Idealized methodology (5/10)
	- Same comment as for "Pollster methodology" below.
- Idealized survey (2/4)
	- Fine.
- Pollster methodology overview and evaluation (5/10)
	- Please demonstrate that you know what these terms mean. What is a target population? What is a probability sample? Why does non-response matter?
- Referencing (0/4)
	- Not done.
- Commits (2/2)
	- Great.
- Sketches (0/2)
	- Desired graph not sketched
- Simulation (3/4)
	- Be more sophisticated.
- Tests-simulation (0/4)
	- Not done.
- Tests-actual (3/4)
	- Add more
- Parquet (0/1)
	- Not done.
- Reproducible workflow (0/4)
	- README not properly updated "as obtained from X."
	- Remove unused files and folders.
	- Comment and close all Issues.
- Miscellaneous (0/3)
	- None.

**Comment by xgao28** [comment]
Thank you! We added R and data citation, the use of parquet, the graph sketches, test-simulation, changed title, readme, removed unused files and folders.
